version: '3'
services:
    miniflux:
        image: netpascal0123/miniflux:experimental
        ports:
            - "3355:8080"
        depends_on:
            - db
        environment:
            - DATABASE_URL=postgres://miniflux:XXXX@db/miniflux?sslmode=disable
            - ADMIN_USERNAME=admin
            - ADMIN_PASSWORD=test123
            - BASE_URL=https://rssfeed.netpascal.site/
        restart: unless-stopped
    dev:
        image: golang-dev
        command: sh
        volumes:
            - .:/data/
        ports:
            - 80:80
        depends_on:
            - db
        environment:
            - DATABASE_URL=postgres://miniflux:XXXX@db/miniflux?sslmode=disable
            - ADMIN_USERNAME=admin
            - ADMIN_PASSWORD=test123
            - LISTEN_ADDR=0.0.0.0:80
    setup:
        image: netpascal0123/miniflux:experimental
        ports:
            - "3355:8080"
        depends_on:
            - db
        environment:
            - DATABASE_URL=postgres://miniflux:XXXX@db/miniflux?sslmode=disable
            - RUN_MIGRATIONS=1
            - CREATE_ADMIN=1
            - ADMIN_USERNAME=admin
            - ADMIN_PASSWORD=test123
            - BASE_URL=https://rssfeed.netpascal.site/
        restart: "no"
    db:
        image: postgres:latest
        environment:
            - POSTGRES_USER=miniflux
            - POSTGRES_PASSWORD=XXXX
        volumes:
            - /media/tinyrssdb/:/var/lib/postgresql/data
        restart: unless-stopped
